name: sqlite
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.0-143.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi_web: '>=0.1.0-dev.1'
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
